config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"

  namespace :ory do
    resource :oauth, only: :new, controller: :oauth do
      member do
        get :callback
      end
    end

    get :permissions, to: "permissions#index"
    get 'check-permissions', to: "permissions#check"
    post 'verify-permissions', to: "permissions#verify"
    get :identities, to: "identities#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ory_oauth_token.rb
class OryOauthToken < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/ory/api_client_initializer.rb
module Ory::ApiClientInitializer
  TOKEN_TYPE = 'api_key'
  API_BASE_URL = ENV['API_BASE_URL']
  AUTH_URL = "/oauth2/auth"
  TOKEN_URL = "/oauth2/token"
  SCOPE = 'openid offline_access'
  CLIENT_ID = ENV['ORY_CLIENT_ID']
  SECRET = ENV['ORY_SECRET']

  def api_client
    @api_client ||= OryKetoClient::ApiClient.new(configuration)
  end

  def oauth_client
    OAuth2::Client.new(CLIENT_ID, SECRET, site: API_BASE_URL, authorize_url: AUTH_URL, token_url: TOKEN_URL)
  end

  def read_api
    @read_api ||= OryKetoClient::ReadApi.new(api_client)
  end

  def request_options
    {
      header_params: authorization_header
    }
  end

  private

  def authorization_header
    {"Authorization"=> "#{configuration.api_key_prefix[TOKEN_TYPE]} #{configuration.api_key[TOKEN_TYPE]}"}
  end

  def configuration
    @config ||= OryKetoClient::Configuration.new do |config|
      config.scheme = 'https'
      config.host = ENV['API_BASE_URL'].split("//").last
      config.api_key[TOKEN_TYPE] = ENV['ORY_API_KEY']
      config.api_key_prefix[TOKEN_TYPE] = 'Bearer'
      config.server_index = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController

  API_BASE_URL = ENV['API_BASE_URL']
  AUTH_URL = "/oauth2/auth"
  TOKEN_URL = "/oauth2/token"
  SCOPE = 'openid offline_access'
  CLIENT_ID = ENV['ORY_CLIENT_ID']
  SECRET = ENV['ORY_SECRET']

  def new
    redirect_to auth_url, allow_other_host: true
  end

  def callback
    if params[:code]
      @token = fetch_tokens
      save_tokens(@token)
    else
      render :error
    end
  end

  private
  def client
    OAuth2::Client.new(CLIENT_ID, SECRET, site: API_BASE_URL, authorize_url: AUTH_URL, token_url: TOKEN_URL)
  end

  def fetch_tokens
    client.auth_code.get_token(
      params[:code],
      redirect_uri: callback_oauth_url
    )
  end

  def auth_url
    client.auth_code.authorize_url(
      scope: SCOPE,
      redirect_uri: callback_url,
      state: SecureRandom.uuid
    )
  end

  def callback_url
    callback_oauth_url
  end

  def save_tokens(token)
    OryOauthToken.create(
      access_token: token.token,
      refresh_token: token.refresh_token,
      expires_at: Time.at(token.expires_at)
    )
  end
end

app/controllers/ory/identities_controller.rb
class  Ory::IdentitiesController < ApplicationController
  include Ory::ApiClientInitializer

  def index
    @users = fetch_identities_from_ory
  end

  private
  def fetch_identities_from_ory
    identities_path = 'admin/identities'
    request = api_client.build_request(:GET, identities_path, request_options)
    JSON.parse(request.run.body)
  end
end

app/controllers/ory/oauth_controller.rb
class Ory::OauthController < ApplicationController
  include Ory::ApiClientInitializer

  def new
    redirect_to auth_url, allow_other_host: true
  end

  def callback
    if params[:code]
      @token = fetch_tokens
      save_tokens(@token)
    else
      render :error
    end
  end

  private

  def fetch_tokens
    oauth_client.auth_code.get_token(
      params[:code],
      redirect_uri: callback_url
    )
  end

  def auth_url
    oauth_client.auth_code.authorize_url(
      scope: SCOPE,
      redirect_uri: callback_url,
      state: SecureRandom.uuid
    )
  end

  def callback_url
    callback_ory_oauth_url
  end

  def save_tokens(token)
    OryOauthToken.create(
      access_token: token.token,
      refresh_token: token.refresh_token,
      expires_at: Time.at(token.expires_at)
    )
  end
end

app/controllers/ory/permissions_controller.rb
class Ory::PermissionsController < ApplicationController
  include Ory::ApiClientInitializer

  def index
    @relation_tuples = fetch_relation_tuples_from_ory
  end

  def check
  end

  def verify
    @allowed = verify_permission
    render :check
  end

  private

  def fetch_relation_tuples_from_ory
    read_api.get_relation_tuples(request_options).relation_tuples
  end

  def verify_permission
    options = permitted_params.to_hash.merge(request_options)
    response = read_api.get_check(options.with_indifferent_access)
    response.allowed
  end

  def permitted_params
    params.permit(:subject_id, :object, :relation, :namespace, :max_depth)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Ory Keto Application</h1>
<ol>
  <li>
    <%= link_to "OAuth2", new_ory_oauth_path %>
  </li>
  <li>
    <%= link_to "Check a permission", ory_check_permissions_path %>
  </li>
  <li>
    <%= link_to "View all permissions", ory_permissions_path %>
  </li>
  <li>
    <%= link_to "View all users (Identities)", ory_identities_path %>
  </li>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OryKetoRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ory/identities/index.html.erb
<%= link_to "Home", root_path %>
<h2>Ory keto users</h2>
<table border="2">
  <thead>
    <th>ID</th>
    <th>Email</th>
    <th>State</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user['id'] %></td>
        <td><%= user['traits']['email'] %></td>
        <td><%= user['state'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ory/oauth/callback.html.erb
<%= link_to "Home", root_path %>
<h3>Authentication Tokens:</h3>
<p>Access Token: <%= @token.token %></p>
<p>Refresh Token: <%= @token.refresh_token %></p>
<p>Expires At: <%= Time.at @token.expires_at %></p>

app/views/ory/oauth/error.html.erb
<%= link_to "Home", root_path %>
<h3>Authorization Error!</h3>
<p>Something went wrong. Please <%= link_to "Try Again.", new_oauth_path %></p>

app/views/ory/permissions/check.html.erb
<%= link_to "Home", root_path %>
<h2>Check ory keto permissions</h2>
<%= form_with(url: ory_verify_permissions_path) do |form| %>

  <% unless @allowed.nil? %>
    <div style="padding: 10px; text-align: center;">
      <b>The permission is <%= @allowed ? "Allowed" : "Not allowed" %></b>
    </div>
  <% end %>

  <div class="form-field">
    <%= form.label :namespace %>
    <%= form.text_field :namespace %>
  </div>

  <div class="form-field">
    <%= form.label :subject_id, 'Subject' %>
    <%= form.text_field :subject_id %>
  </div>

  <div class="form-field">
    <%= form.label :relation %>
    <%= form.text_field :relation %>
  </div>

  <div class="form-field">
    <%= form.label :object %>
    <%= form.text_field :object %>
  </div>

  <div class="form-field">
    <%= form.label :max_depth %>
    <%= form.text_field :max_depth %>
  </div>

  <div class="">
    <%= form.submit 'Check' %>
  </div>
<% end %>

app/views/ory/permissions/index.html.erb
<%= link_to "Home", root_path %>
<h2>Ory keto permissions</h2>
<table border="2">
  <thead>
    <th>Subject</th>
    <th>Relation</th>
    <th>Object</th>
    <th>Namespace</th>
  </thead>
  <tbody>
    <% @relation_tuples.each do |tuple| %>
      <tr>
        <td><%= tuple.subject_id %></td>
        <td><%= tuple.relation %></td>
        <td><%= tuple.object %></td>
        <td><%= tuple.namespace %></td>
      </tr>
    <% end %>
  </tbody>
</table>